name: example
description: Example of Adaptive Cards.
author: Neohelden GmbH <hello@neohelden.com>
homepage: https://neohelden.com
version: 0.1.0

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dynamic_theme: ^1.0.1
  url_launcher: ^5.4.7
  flutter_adaptive_cards:
    path: ..

  cupertino_icons: ^0.1.2
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/neo_logo_light.png
    - assets/neo_logo.png
    - assets/norbert.jpg
    - assets/pascal.jpg
    - assets/banner.jpg
    - lib/easy_card
    - lib/adaptive_card_string
    - lib/host_config
    - lib/activity_update
    - lib/text_block/example1
    - lib/text_block/example2
    - lib/text_block/example3
    - lib/text_block/example4
    - lib/text_block/example5
    - lib/text_block/example5
    - lib/text_block/example6
    - lib/text_block/example7
    - lib/text_block/example8
    - lib/text_block/example9
    - lib/text_block/example10
    - lib/image/example1
    - lib/image/example2
    - lib/image/example3
    - lib/image/example4
    - lib/image/example5
    - lib/image/example5
    - lib/image/example6
    - lib/container/example1
    - lib/container/example2
    - lib/container/example3
    - lib/container/example4
    - lib/container/example5
    - lib/column_set/example1
    - lib/column_set/example2
    - lib/column_set/example3
    - lib/column_set/example4
    - lib/column_set/example5
    - lib/column_set/example6
    - lib/column/example1
    - lib/column/example2
    - lib/column/example3
    - lib/column/example4
    - lib/column/example5
    - lib/fact_set/example1
    - lib/image_set/example1
    - lib/image_set/example2
    - lib/action_set/example1
    - lib/action_open_url/example1
    - lib/action_open_url/example2
    - lib/action_submit/example1
    - lib/action_show_card/example1
    - lib/inputs/input_text/example1
    - lib/inputs/input_text/example2
    - lib/inputs/input_number/example1
    - lib/inputs/input_date/example1
    - lib/inputs/input_time/example1
    - lib/inputs/input_time/example2
    - lib/inputs/input_toggle/example1
    - lib/inputs/input_choice_set/example1
    - lib/media/example1
    - lib/samples/example1
    - lib/samples/example2
    - lib/samples/example3
    - lib/samples/example4
    - lib/samples/example5
    - lib/samples/example6
    - lib/samples/example7
    - lib/samples/example8
    - lib/samples/example9
    - lib/samples/example10
    - lib/samples/example11
    - lib/samples/example12
    - lib/samples/example13
    - lib/samples/example14
    - lib/samples/example15
